'use strict';

const Joi = require('joi');
const { randomUUID } = require('node:crypto');
const { ErrorResponse } = require('../middleware/errorHandler');

/**
 * Identity is generated by the application, not by a column default.
 *
 * A `gen_random_uuid()` default only exists on Postgres, so on any other
 * engine - including the SQLite the test suite runs on - inserts came back
 * with a null id and every follow-up request 404'd. Generating here makes the
 * id available before the round trip and keeps the code portable.
 */
const newId = () => randomUUID();

/**
 * Shared route plumbing.
 *
 * The five resource routers below all do the same four things: validate input,
 * page a list, scope rows to the caller's company, and shape a response. Doing
 * that once here is what keeps a bug fixed in one place rather than five, and
 * what makes every endpoint in the README answer with the same envelope.
 */

/** Every list endpoint pages the same way, so clients learn it once. */
const paginationSchema = Joi.object({
  page: Joi.number().integer().min(1).default(1),
  limit: Joi.number().integer().min(1).max(100).default(25),
  sort: Joi.string().max(40),
  order: Joi.string().valid('asc', 'desc').default('desc')
}).unknown(true);

/**
 * Validate one part of the request and REPLACE it with the validated value, so
 * handlers read coerced types (numbers as numbers, defaults applied) instead of
 * re-parsing strings and disagreeing about the answer.
 */
function validate(schema, source = 'body') {
  return (req, res, next) => {
    const { error, value } = schema.validate(req[source], {
      abortEarly: false,
      stripUnknown: source === 'body',
      convert: true
    });

    if (error) {
      return next(new ErrorResponse('Validation failed', 400, {
        code: 'VALIDATION_ERROR',
        fields: error.details.map((d) => ({ field: d.path.join('.'), message: d.message }))
      }));
    }
    // req.query is a getter on newer Express; assign defensively.
    if (source === 'query') Object.defineProperty(req, 'query', { value, writable: true });
    else req[source] = value;
    return next();
  };
}

function paginate(query) {
  const page = query.page || 1;
  const limit = query.limit || 25;
  return { page, limit, offset: (page - 1) * limit };
}

const meta = (total, { page, limit }) => ({
  page,
  limit,
  total,
  pages: Math.max(1, Math.ceil(total / limit))
});

/**
 * Scope a query to the caller's company.
 *
 * This is the single most important line in the API: without it a user of one
 * restoration company can read another's properties, leads and estimates. It
 * lives here so no resource router can forget it, and platform admins are the
 * only role that opts out.
 */
function scopeToCompany(query, user, column = 'company_id') {
  if (user?.role === 'admin' && user?.platform_admin) return query;
  return query.where(column, user.company_id);
}

/** 404 that reads the same whichever resource is missing. */
const notFoundIf = (row, what) => {
  if (!row) throw new ErrorResponse(`${what} not found`, 404, { code: 'NOT_FOUND' });
  return row;
};

/** Geographic bounds appear in three routers; parse them one way. */
const boundsSchema = Joi.object({
  north: Joi.number().min(-90).max(90).required(),
  south: Joi.number().min(-90).max(90).required(),
  east: Joi.number().min(-180).max(180).required(),
  west: Joi.number().min(-180).max(180).required()
});

const coordinateSchema = {
  latitude: Joi.number().min(-90).max(90),
  longitude: Joi.number().min(-180).max(180)
};

/**
 * Bounding box for a radius search, so the SQL can use the lat/lng index before
 * the exact distance is computed. One degree of latitude is ~111km everywhere;
 * longitude shrinks by cos(latitude), which matters a lot at high latitudes.
 */
function radiusBox(lat, lng, miles) {
  const km = miles * 1.60934;
  const dLat = km / 111;
  const dLng = km / (111 * Math.max(0.01, Math.cos((lat * Math.PI) / 180)));
  return { north: lat + dLat, south: lat - dLat, east: lng + dLng, west: lng - dLng };
}

/** Great-circle distance in miles, for ordering and for the exact filter. */
function distanceMiles(lat1, lng1, lat2, lng2) {
  const toRad = (d) => (d * Math.PI) / 180;
  const R = 3958.8;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}

module.exports = {
  Joi,
  newId,
  validate,
  paginate,
  meta,
  scopeToCompany,
  notFoundIf,
  paginationSchema,
  boundsSchema,
  coordinateSchema,
  radiusBox,
  distanceMiles
};
